### ISSUE TITLE
Get Injected DocumentStore

### ISSUE THREAD

**Issue by Yucked** [PassiveModding/Lithium#1]
Instead of creating `new DocumentStore`, use the one that is injected already.

```cs
static IDocumentStore Store { get; set; }
public DatabaseHandler(IDocumentStore store) => Store = store;
```

Otherwise it's going to use a lot more resources.

https://github.com/PassiveModding/Lithium/blob/4559960ff888b6273983f4c5add6e0cb6add60c9/Lithium/Handlers/DatabaseHandler.cs#L26

https://github.com/PassiveModding/Lithium/blob/4559960ff888b6273983f4c5add6e0cb6add60c9/Lithium/Handlers/DatabaseHandler.cs#L67

https://github.com/PassiveModding/Lithium/blob/4559960ff888b6273983f4c5add6e0cb6add60c9/Lithium/Handlers/DatabaseHandler.cs#L85

https://github.com/PassiveModding/Lithium/blob/4559960ff888b6273983f4c5add6e0cb6add60c9/Lithium/Handlers/DatabaseHandler.cs#L133

https://github.com/PassiveModding/Lithium/blob/4559960ff888b6273983f4c5add6e0cb6add60c9/Lithium/Handlers/DatabaseHandler.cs#L144

**Comment by PassiveModding** [comment]
https://github.com/PassiveModding/Lithium/commit/655f0344a66b52b5f35097fa75d7187e1323b592
Thanks!!
