### ISSUE TITLE
System.InvalidOperationException in DatabaseHander.

### ISSUE THREAD

**Issue by TylerFlar** [PassiveModding/Lithium#2]
I'm getting an issue with:
`return Session.Load<GuildModel.Guild>(Id.ToString());` In DatabaseHandler line 154 when starting the bot.

It's saying "System.InvalidOperationException: 'Could not convert document 318568010937925642 to entity of type PassiveBot.Models.GuildModel+Guild'."

The Inner Exception is:

>Inner Exception 1:
JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.String' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Settings.Prefix.DenyMentionPrefix.Settings.Prefix.DenyMentionPrefix'.

Are you getting this error too?

(On a side note I also have been getting "An {Insert handler here} is blocking the gateway task" if that makes a difference which I think not).

**Comment by PassiveModding** [comment]
do you know which commit you used last?

**Comment by PassiveModding** [comment]
Please open this issue on the right repo as well, You opened this in lithium but it seems like you are trying to use https://github.com/PassiveModding/Passive-BOT
based on the stack trace

**Comment by TylerFlar** [comment]
Sorry, it's actually with Lithium. I was writing the issue by memory and by mistake put "PassiveBot."

And it's with the current version

**Comment by PassiveModding** [comment]
Well the stack trace is referencing stuff specific to PassiveBOT (DenyMentionPrefix) and PassiveBot.Models.GuildModel+Guild, could you please verify this and send an issue that is specific to the bot

**Comment by PassiveModding** [comment]
The only issue I could really say is could it be possible that you've used both bots and given them the same database name? Because that would create some pretty serious conflicts

**Comment by TylerFlar** [comment]
Yep, that was it. Was tired yesterday so probably missed that. 
Thanks!
